project:
  output-dir: ./_site/
book:
  title: "Büyük Dil Modelleri Giriş Ders Notları"

  chapters:
    - course-notes/tokenize-tr.qmd
    - course-notes/embedding-tr.qmd
    - course-notes/dot-product-vs-cosine-similarity-en.md
    - course-notes/sozluk.qmd




