```{mermaid}
%%| label: fig-dump-language-model-2
%%| fig-width: 15
flowchart TD
    LM["Dump Language Model "] -->|"Randomly generates output "| P
    P("$$p=\frac{1}{100}$$")
    P --> L1("$$ L = -ln(p) $$")
    L1 --> L2("$$ 4.60  $$")
```
