```{mermaid}
flowchart LR
    Input[Example input here] -->|Tokenize decode| InputTokens
    InputTokens["16281, 5128, 994"] --> LLM
    LLM("LLM<img src='https://ati-ozgur.github.io/course-nn-deep-learning/cover.png'; width='50' />")
    LLM -->OutputTokens 
    OutputTokens["16281, 5072, 994"]  -->|Tokenize decode| Output
    Output["Example output here"]
```