```{mermaid}
%%| fig-width: 6.5
flowchart LR
    Input[Example input here] -->|Tokenize decode| InputTokens
    InputTokens["16281, 5128, 994"] --> LLM
    LLM("LLM")
    LLM -->OutputTokens 
    OutputTokens["16281, 5072, 994"]  -->|Tokenize decode| Output
    Output["Example output here"]
```